import {Metadata} from "next";
import Navigation from "../components/navigation";
import "../styles/global.css"


// meta data 는 SSR 에서만 작동.
export const metadata: Metadata = {
  title: {
    template : '%s | Next Js.',
    default : 'Loading...'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
